import { env } from "process";

export const DIALECT = "mariadb";

const LOCAL_CONFIGURATION = {
  DB: "b2b-app",
  PASSWORD: "Cadem2018Dev",
  PORT_DB: 3306,
  SERVER: "localhost",
  USER_DB: "cademsmart",
};

const ICB_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_ICB_PASSWORD,
  PORT_DB: Number(env.B2B_ICB_PORT),
  SERVER: env.B2B_ICB_SERVER,
  USER_DB: env.B2B_ICB_USERNAME,
};

const PERNOD_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_PERNOD_PASSWORD,
  PORT_DB: Number(env.B2B_PERNOD_PORT),
  SERVER: env.B2B_PERNOD_SERVER,
  USER_DB: env.B2B_PERNOD_USERNAME,
};

const ANDINA_PRODUCTION = {
  DB: "b2b-andina-app",
  PASSWORD: env.B2B_ANDINA_PASSWORD,
  PORT_DB: Number(env.B2B_ANDINA_PORT),
  SERVER: env.B2B_ANDINA_SERVER,
  USER_DB: env.B2B_ANDINA_USERNAME,
};

const ABI_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_ABI_PASSWORD,
  PORT_DB: Number(env.B2B_ABI_PORT),
  SERVER: env.B2B_ABI_SERVER,
  USER_DB: env.B2B_ABI_USERNAME,
};

const CIAL_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_CIAL_PASSWORD,
  PORT_DB: Number(env.B2B_CIAL_PORT),
  SERVER: env.B2B_CIAL_SERVER,
  USER_DB: env.B2B_CIAL_USERNAME,
};

const YOGEN_LITE_PRODUCTION = {
  DB: "qa-encuestas-app",
  PASSWORD: env.B2B_YOGEN_LITE_PASSWORD,
  PORT_DB: Number(env.B2B_YOGEN_LITE_PORT),
  SERVER: env.B2B_YOGEN_LITE_SERVER,
  USER_DB: env.B2B_YOGEN_LITE_USERNAME,
};

const EMBONOR_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_EMBONOR_PASSWORD,
  PORT_DB: Number(env.B2B_EMBONOR_PORT),
  SERVER: env.B2B_EMBONOR_SERVER,
  USER_DB: env.B2B_EMBONOR_USERNAME,
};

const DEMO_PRODUCTION = {
  DB: "b2b-app",
  PASSWORD: env.B2B_DEMO_PASSWORD,
  PORT_DB: Number(env.B2B_DEMO_PORT),
  SERVER: env.B2B_DEMO_SERVER,
  USER_DB: env.B2B_DEMO_USERNAME,
};

const CADEM_ABI_BI_PRODUCTION = {
  DB: "cadem_abi_bi",
  PASSWORD: env.CADEM_ABI_BI_PASSWORD,
  PORT_DB: Number(env.CADEM_ABI_BI_PORT_DB),
  SERVER: env.CADEM_ABI_BI_SERVER,
  USER_DB: env.CADEM_ABI_BI_USERNAME,
};

export const config = {
  DEMO_DB: DEMO_PRODUCTION,
  ABI_DB: ABI_PRODUCTION,
  CIAL_DB: CIAL_PRODUCTION,
  YOGEN_LITE_DB: YOGEN_LITE_PRODUCTION,
  EMBONOR_DB: EMBONOR_PRODUCTION,
  ANDINA_DB: ANDINA_PRODUCTION,
  CADEM_ABI_BI_DB: CADEM_ABI_BI_PRODUCTION,
  PERNOD_DB: PERNOD_PRODUCTION,
  ICB_DB: ICB_PRODUCTION,
  PORT_APP: 1344,
  SECRET: "C4d3m#Sm4rt_#!",
  DEMO_B2B: {
    ...DEMO_PRODUCTION,
    DB: "b2b-data",
  },
  PERNOD_B2B: {
    ...PERNOD_PRODUCTION,
    DB: "b2b-pernod",
  },
  ICB_B2B: {
    ...ICB_PRODUCTION,
    DB: "b2b-icb",
  },
  ANDINA_B2B: {
    ...ANDINA_PRODUCTION,
    DB: "b2b-andina",
  },
  ABI_B2B: {
    ...ABI_PRODUCTION,
    DB: "b2b-abi",
  },
  CIAL_B2B: {
    ...CIAL_PRODUCTION,
    DB: "b2b-cial",
  },
  YOGEN_LITE_B2B: {
    ...YOGEN_LITE_PRODUCTION,
    DB: "qa-encuestas-app",
  },
  EMBONOR_B2B: {
    ...EMBONOR_PRODUCTION,
    DB: "b2b-embonor",
  },
  SOURCE_MASTER: {
    DB: env.SOURCE_MASTER_DB,
    PASSWORD: env.SOURCE_MASTER_PASSWORD,
    PORT_DB: Number(env.SOURCE_MASTER_PORT_DB),
    SERVER: env.SOURCE_MASTER_SERVER,
    USER_DB: env.SOURCE_MASTER_USER_DB,
  },
  SOURCE_PRINCIPAL: {
    DB: env.SOURCE_PRINCIPAL_DB,
    PASSWORD: env.SOURCE_PRINCIPAL_PASSWORD,
    PORT_DB: Number(env.SOURCE_PRINCIPAL_PORT_DB),
    SERVER: env.SOURCE_PRINCIPAL_SERVER,
    USER_DB: env.SOURCE_PRINCIPAL_USER_DB,
  },
  SOURCE_SUPI: {
    DB: env.SOURCE_SUPI_DB,
    PASSWORD: env.SOURCE_SUPI_PASSWORD,
    PORT_DB: Number(env.SOURCE_SUPI_PORT_DB),
    SERVER: env.SOURCE_SUPI_SERVER,
    USER_DB: env.SOURCE_SUPI_USER_DB,
  },
  SMARTWEB: {
    CIAL: {
      DB: env.SOURCE_SMARTWEB_CIAL_DB,
      PASSWORD: env.SOURCE_SMARTWEB_CIAL_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_CIAL_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_CIAL_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_CIAL_USER_DB,
    },
    YOGEN_LITE: {
      DB: env.SOURCE_SMARTWEB_CIAL_DB,
      PASSWORD: env.SOURCE_SMARTWEB_CIAL_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_CIAL_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_CIAL_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_CIAL_USER_DB,
    },
    EMBONOR: {
      DB: env.SOURCE_SMARTWEB_EMBONOR_DB,
      PASSWORD: env.SOURCE_SMARTWEB_EMBONOR_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_EMBONOR_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_EMBONOR_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_EMBONOR_USER_DB,
    },
    ANDINA: {
      DB: env.SOURCE_SMARTWEB_ANDINA_DB,
      PASSWORD: env.SOURCE_SMARTWEB_ANDINA_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_ANDINA_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_ANDINA_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_ANDINA_USER_DB,
    },
    ABI: {
      DB: env.SOURCE_SMARTWEB_ABI_DB,
      PASSWORD: env.SOURCE_SMARTWEB_ABI_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_ABI_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_ABI_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_ABI_USER_DB,
    },
    PERNOD: {
      DB: env.SOURCE_SMARTWEB_PERNOD_DB,
      PASSWORD: env.SOURCE_SMARTWEB_PERNOD_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_PERNOD_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_PERNOD_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_PERNOD_USER_DB,
    },
    ICB: {
      DB: env.SOURCE_SMARTWEB_ICB_DB,
      PASSWORD: env.SOURCE_SMARTWEB_ICB_PASSWORD,
      PORT_DB: Number(env.SOURCE_SMARTWEB_ICB_PORT_DB),
      SERVER: env.SOURCE_SMARTWEB_ICB_SERVER,
      USER_DB: env.SOURCE_SMARTWEB_ICB_USER_DB,
    },
  },
  KM: env.KM,
};

export const AWS_CREDENTIALS = {
  accessKeyId: env.AWS_CREDENTIALS_accessKeyId,
  secretAccessKey: env.AWS_CREDENTIALS_secretAccessKey,
};
